repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
     - id: isort
       args: ["--profile", "black", "--filter-files"]
       verbose: true
  -   repo: https://github.com/pycqa/flake8
      rev: '3.9.2'
      hooks:
        -   id: flake8
            args:
              - "--max-line-length=88"
              - "--max-complexity=18"
              - "--select=B,C,E,F,W,T4,B9"
              - "--ignore=E203,E266,E501,W503"
