name: CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-unittest:
    name: Linux unittest - ${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda cache
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key:
            mamba--${{ hashFiles('environment.yml') }}-${{ matrix.PYTHON_VERSION }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: lleaves
          environment-file: environment.yml
          use-only-tar-bz2: true
          use-mamba: true
      - name: Setup hypothesis DB cache
        uses: actions/cache@v3
        with:
          path: ./.hypothesis
          key: hypothesisDB ${{ matrix.PYTHON_VERSION }}
      - name: Run the unittests
        shell: bash -x -l {0}
        run: ./.github/ci.sh ${{ matrix.PYTHON_VERSION }}
      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && matrix.PYTHON_VERSION == '3.7'
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  pre-commit-checks:
    name: "Pre-commit checks - Python 3.9"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
